version: "3.3"
services:
  
  cronjobs:
    container_name: cronjobs
    build: .
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESUSER}
      POSTGRES_PASSWORD : ${POSTGRESPASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  # used to query the database before implementing UI
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  flask:
    container_name: flask
    build:
      context: "."
      dockerfile: "./app/Dockerfile"
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000

  nginx:
    build: ./nginx
    container_name: nginx
    #environment:
    #  - SERVER_NAME=${NGINX_SERVER_NAME}
    ports:
      - "80:80"
    restart: always

volumes:
  db:
    driver: local